# Build the test suite for Android libsndfile
# 2023, Sylvain Carette, based on the original CMakeLists.txt from libsndfile

# Initial set up

cmake_minimum_required (VERSION 3.0)

# Do not run this script if using MSVC compiler
if (CMAKE_SYSTEM_NAME STREQUAL "Android" AND MSVC)
    message(FATAL_ERROR "Error: Must use Clang to compile for Android, not MSVC.")
endif()

# Locate config.h
set(CONFIG_H_FILE "${CMAKE_CURRENT_BINARY_DIR}/src/config.h")

# Extract PACKAGE_VERSION
file(STRINGS ${CONFIG_H_FILE} PACKAGE_VERSION_DEFN REGEX "#define PACKAGE_VERSION")
string(REGEX REPLACE "#define PACKAGE_VERSION \"([^\"]+)\"" "\\1" PACKAGE_VERSION ${PACKAGE_VERSION_DEFN})

# Extract LIB_VERSION
string(REGEX REPLACE "([0-9]+\\.[0-9]+\\.[0-9]+).*" "\\1" LIB_VERSION ${PACKAGE_VERSION})

# Set the absolute source directory
set(ABS_TOP_SRCDIR "${CMAKE_CURRENT_SOURCE_DIR}")

# Set the archive name
set(ARCHIVE_NAME "libsndfile-testsuite-${TARGET_ARCHITECTURE}")

# Set the tarball name
set(TARBALL "${ARCHIVE_NAME}.tar.gz")

# User definable device path to the test script - default to data/local/tmp
set(DEVICE_TESTS_PATH "/data/local/tmp/${ARCHIVE_NAME}/lib")

# Set path and script content for the binheader and pedantic tests
set(PYTHON_EXECUTABLE "/usr/bin/python")

set(RUN_PH_TEST_CONTENT "#!/bin/bash
echo \"Running pedantic-header-test\"
/bin/sh ${CMAKE_CURRENT_BINARY_DIR}/../tests/pedantic-header-test.sh > ${CMAKE_CURRENT_BINARY_DIR}/pedantic_test_result 2>&1
if [[ -s ${CMAKE_CURRENT_BINARY_DIR}/pedantic_test_result ]]; then
	content=$(<\"${CMAKE_CURRENT_BINARY_DIR}/pedantic_test_result\")
	sed -i \"s/<PLACEHOLDER_PEDANTIC_TEST_RESULT>/\$content/g\" \"${CMAKE_CURRENT_BINARY_DIR}/test_wrapper.sh\"
else
    echo \"pedantic_test_result is empty\"
    exit 1
fi
") # End RUN_PH_TEST_CONTENT

file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/run_ph_test.sh "${RUN_PH_TEST_CONTENT}")
file(CHMOD ${CMAKE_CURRENT_BINARY_DIR}/run_ph_test.sh PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ)


# Create the first content segment for test_wrapper file
set(TEST_WRAPPER_CONTENT "#!/system/bin/sh

# Build the test suite for Android libsndfile
# 2023, Sylvain Carette, based on the original CMakeLists.txt from libsndfile
# This file is generated by CMake
# Copyright (C) 2008-2017 Erik de Castro Lopo <erikd@mega-nerd.com>
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#     * Neither the author nor the names of any contributors may be used
#       to endorse or promote products derived from this software without
#       specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


HOST_TRIPLET=${TARGET_ARCHITECTURE}
PACKAGE_VERSION=${PACKAGE_VERSION}
LIB_VERSION=${LIB_VERSION}

# Set target device library path
export LD_LIBRARY_PATH=\${pwd}/lib:$LD_LIBRARY_PATH

echo \"Starting tests...\"

sfversion=\$(./tests/sfversion | grep libsndfile | sed \"s/-exp\$//\")

if test \"$sfversion\" != libsndfile-$PACKAGE_VERSION ; then
	echo \"Error : sfversion (\$sfversion) and PACKAGE_VERSION ($PACKAGE_VERSION) don't match.\"
	exit 1
	fi

# Force exit on errors.
set -e

") # End first segment TEST_WRAPPER_CONTENT


# Create the command script file
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/test_wrapper.sh "${TEST_WRAPPER_CONTENT}")

# Macro to add a milestone to the command script
macro(add_milestone message)
	set(echo_line "echo \"  $sfversion ${message}\"\n")
	file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/test_wrapper.sh "echo \"----------------------------------------------------------------------\"\n")
	file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/test_wrapper.sh "${echo_line}")	
	file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/test_wrapper.sh "echo \"----------------------------------------------------------------------\"\n")
endmacro(add_milestone)

# Macro to add test to the command script
macro(add_android_test test_name)
	file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/test_wrapper.sh "./tests/${test_name}\n")
endmacro(add_android_test)

# Macro to add test with arguments to the command script
macro(add_android_test_args test_name args)
	file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/test_wrapper.sh "./tests/${test_name} ${args}\n")
endmacro(add_android_test_args)

# Keep a list of all the test programs for the tarball
set(TEST_PROGRAMS_LIST "")

# Add pedantic header test to the command script
# Ensure the placeholder is there
file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/test_wrapper.sh "# Check the header file.\necho \"<PLACEHOLDER_PEDANTIC_TEST_RESULT>\"\n\n")
# As we don't have a C compiler on the target, and as we also need the library, we perform this test post-build
add_custom_target(run_phtest ALL
    COMMAND ${CMAKE_CURRENT_BINARY_DIR}/run_ph_test.sh
    COMMENT "Running post-build pedantic header test"
)
add_dependencies(run_phtest sndfile)


# Here we continue with almost as the original libsndfile CMakeLists.txt

include (CMakeAutoGen)

# generate tests sources from autogen templates

macro (wrap_test_sources)
	foreach (test_source ${ARGN})
		get_filename_component (test_name ${test_source} NAME_WE)
		file (READ ${test_source} test_content)
		string (REGEX REPLACE "int[[:space:]]+main[[:space:]]*\\(([^)]*)\\)" "${test_name}_wrapper(\\1)" wrapped_content "${test_content}")
		file (WRITE ${CMAKE_CURRENT_BINARY_DIR}/${test_name}_wrapped.c "${wrapped_content}")
		list (APPEND wrapped_test_sources ${CMAKE_CURRENT_BINARY_DIR}/${test_name}_wrapped.c)
	endforeach ()
	set (WRAPPED_TEST_SOURCES ${wrapped_test_sources} PARENT_SCOPE)
endmacro ()
lsf_autogen (tests benchmark c)
lsf_autogen (tests floating_point_test c)
lsf_autogen (tests header_test c)
lsf_autogen (tests pcm_test c)
lsf_autogen (tests pipe_test c)
lsf_autogen (tests rdwr_test c)
lsf_autogen (tests scale_clip_test c)
lsf_autogen (tests utils c h)
lsf_autogen (tests write_read_test c)
lsf_autogen (src test_endswap c)

# utils static library
add_library(test_utils STATIC tests/utils.c)
target_include_directories (test_utils
	PUBLIC
		src
		${CMAKE_CURRENT_BINARY_DIR}/src
		${CMAKE_CURRENT_BINARY_DIR}/tests
	)
target_link_libraries(test_utils PRIVATE sndfile)

### test_main

add_executable (test_main
	src/test_main.c
	src/test_main.h
	src/test_conversions.c
	src/test_float.c
	src/test_endswap.c
	src/test_audio_detect.c
	src/test_log_printf.c
	src/test_file_io.c
	src/test_ima_oki_adpcm.c
	src/test_strncpy_crlf.c
	src/test_broadcast_var.c
	src/test_cart_var.c
	src/test_binheader_writef.c
	src/test_nms_adpcm.c
	)
target_include_directories (test_main
	PUBLIC
		src
		${CMAKE_CURRENT_BINARY_DIR}/src
		${CMAKE_CURRENT_BINARY_DIR}/tests
	)
target_link_libraries (test_main PRIVATE sndfile)
add_android_test (test_main test_main)
list(APPEND TEST_PROGRAMS_LIST tests/test_main)

### sfversion_test

add_executable (sfversion tests/sfversion.c)
target_include_directories (sfversion
	PRIVATE
		src
		${CMAKE_CURRENT_BINARY_DIR}/src
	)
target_link_libraries (sfversion sndfile)
# No need to add this test to the command script as it is already done in the first segment
list(APPEND TEST_PROGRAMS_LIST tests/sfversion)



# Run the Python script and check result
# As we don't have python on the target, we need to perform this test as we build the test suite
file(GLOB BINHEADER_SOURCES "${ABS_TOP_SRCDIR}/src/*.c")
execute_process(
    COMMAND ${PYTHON_EXECUTABLE} "${ABS_TOP_SRCDIR}/src/binheader_writef_check.py" ${BINHEADER_SOURCES} 
    RESULT_VARIABLE BINHEADER_TEST_RESULT
    OUTPUT_VARIABLE BINHEADER_TEST_OUTPUT
    ERROR_VARIABLE BINHEADER_TEST_ERROR
)

# Embed the result in the test script
if(${BINHEADER_TEST_RESULT} EQUAL 0)
	string(STRIP ${BINHEADER_TEST_OUTPUT} BINHEADER_CLEAN_OUTPUT)
    add_milestone(${BINHEADER_CLEAN_OUTPUT})
else()
	file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/test_wrapper.sh "echo 'binheader_writef_check.py failed:'\n")
	file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/test_wrapper.sh "cat <<EOF\n${BINHEADER_TEST_ERROR}\nEOF\n")
endif()


set (SNDFILE_TEST_TARGETS
		test_utils
		test_main
		sfversion
		)

set_target_properties(${SNDFILE_TEST_TARGETS} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "tests")


# Add the test programs to the tarball
add_custom_target(create_tarball
	COMMAND tar "czf" "${ARCHIVE_NAME}.tar.gz" --transform "s,^,${ARCHIVE_NAME}/," ${TEST_PROGRAMS_LIST} "${CMAKE_INSTALL_LIBDIR}/libsndfile.a" "test_wrapper.sh"
    COMMENT "Creating tarball for testsuite"
)

install(CODE "execute_process(COMMAND ${CMAKE_COMMAND} --build ${CMAKE_BINARY_DIR} --target create_tarball)")
